### PR TITLE
Update the size of Luther image

### PR DESCRIPTION
**Pull request by mrakhsha**
Height of the image is 243 and not 244

### CODE REVIEW

**Comment by bnmnetp** [comment]
Hmm, what browser and platform are you using?  I just checked on Safari on my iPad and it prints the height of the image as 244.  It’s been 244 for years, so I would like to figure out why you are seeing 243

**Comment by mrakhsha** [comment]
Hi Bradley, I used Google Chrome on Mac OsX.

**Comment by bnmnetp** [comment]
OK thanks.  I’m traveling with just my iPad for the next couple weeks, so I won’t be able to do anything more with this until I get back.  I did check both Chrome and Firefox on my iPad and both report a height of 244.

**Comment by mrakhsha** [comment]
Thanks. I'll also try it on other OSs to see if it was the problem of my laptop browser.

**Comment by yarikoptic** [comment]
hm, the image size is indeed 244, so if anything to be fixed - it should be the code somewhere
```shell
$> file ./_sources/_static/LutherBellPic.jpg
./_sources/_static/LutherBellPic.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=1], baseline, precision 8, 400x244, frames 3
```
also for me prints 244 on Version 72.0.3626.7 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

**Comment by mrakhsha** [comment]
I also ran it on an iMac on Google Chrome, it is giving 244.

**Pull request closed without merging**
