### PR TITLE
Fixing links (thanks to Willem Pretorius)

### PR DESCRIPTION
**Pull request by tnbai**
Not sure if this works - referenced other examples

### CODE REVIEW

**Comment by bnmnetp** [comment]
please test it and let me know when you know it works.

**Comment by tnbai** [comment]
I haven't figured out how to test the links, would you have any advice?

**Comment by bnmnetp** [comment]
Build the book and click on them.

1. pip install runestone
2. from the fopp folder `pip build --all serve`. This will let you view the book in your browser by running a little test server.

**Comment by tnbai** [comment]
I was able to successfully run the first command but the second command is giving me ERROR: unknown command "build". I checked that I'm in my fopp directory and have the latest version of pip installed, and I wasn't able to find much related on Google/Slack

**Comment by bnmnetp** [comment]
Ooops, I should proofread my comments the command is `runestone build --all serve`. Which if you read the README for Runestone Components you would have seen. 😄

**Comment by tnbai** [comment]
I can build the textbook now! Very cool. Thanks for your continued help!

**Comment by bnmnetp** [comment]
Thats great!  Just let me know when you have verified that your changes to the links work, and I'll accept the PR.

**Comment by tnbai** [comment]
The changes in my newest commit work!

**Comment by bnmnetp** [comment]
Awesome!  Thank you for your help.

**Pull request merged**
