### PR TITLE
add variables to control aspects of the book and layout

### PR DESCRIPTION
**Pull request by mlhess**
### Description 
This add 2 vars to pavement.py
lockdown will remove all social and items that are not required for Michigan. 
 google_ga_account will allow you to provide a GA account code via pavement. This is set to the Michigan one at the moment. 

I have also set the master_url to '', which should force the book to use relative URLS. 

### Testing

Compile the book and validate the items that are gone should be gone, and that there are no side effects from the master_url change.

### CODE REVIEW

**Comment by bnmnetp** [comment]
Does this belong here?  Or should this be part of server?

**Comment by presnick** [comment]
It needs to be in both places, I think. Here for static pages, server for dynamic pages.

**Comment by mlhess** [comment]
Yes. it goes in both places.   We should make a callback at some point that lets me load the page frame from the server, so the books and the server can use the same structures (header, footer, etc) .

**Comment by bnmnetp** [comment]
closing this as layout.html has been moved to runestone components.

**Pull request closed without merging**
