### PR TITLE
Chapter2

### PR DESCRIPTION
**Pull request by laumurph**
Should be everything for chapter 2 so far. I have two sections from Steve's video on print and input that I'd like to add but I'm not sure how to do so since I'm not (at least currently) hosting the parts of the video on any online platform like it seems to expect. Additionally, I didn't include the page on hard-coding - I'm under the impression that anything labeled as pink should not be included in the general page, only in a separate branch. I'll add a pip misc branch for this kind of stuff later.

### CODE REVIEW

**Comment by bnmnetp** [comment]
Hmm, these conflicts cause major major problems.   Did you make the branch from master or is this a branch from your original branch??

**Comment by laumurph** [comment]
I had branched from the master, but I had gotten rid of the first chapter content when I made this branch since I wanted to keep the branches separate, not building off each other. Would the conflicts be solved by adding the pages back in?

**Comment by bnmnetp** [comment]
I'm thinking through all of this...  I think that all of your PRs have the same conflict and do the same thing which is to mess up the first three chapters...  I need to experiment a bit more to see how we can get out of this with the least bother.

**Comment by laumurph** [comment]
I made a copy of the master and chapter 2 branches and manually added in the content from chapter 2 to the copy branch. It seemed like I was able to merge the two branches together without too much trouble, but that might not be the most practical solution.

**Comment by bnmnetp** [comment]
So I worked through the merge conflicts in the chapter2 branch and the debugging branch.  The problem is that when I'm done there's nothing left in those chapters..  Once I get through those then the next couple of chapters seemed to go fine.

I think the best strategy will be for me to accept debugging and chapter2 . Then you will need to do a fresh PR to add back those files that are gone from your repository again.

**Comment by bnmnetp** [comment]
if you update your master from the main fopp repository.
Then on your branch you can do a git merge master to undo the deletes.  

I think the problem is that your first PR was on your master rather than a branch, so when you branched from master you inherited the deletes...  I'm going to clone your repository and see if I can figure out a clean solution.

**Comment by bnmnetp** [comment]
I'm struggling to figure out a better way to deal with this.  The problem is that GeneralIntro was on master and ALL of your branches delete GeneralIntro...

I think that the best way to get out of this may be to have you make a fresh Fork of the master repo (but don't delete your local copy!!)  Then clone this new fork into a different folder.  Next you will need to remake your branches in the new clone by first branching and then copying over the files from the folder from the old clone.  You or I will need to close the current set of PR's

If you push and re-make your PRs this should work.

Lets give that a shot on a couple and see if we get rid of the merge conflicts.

There is a way to use rebase to remove a particular commit, but it doesn't look like all of the times you removed chapter 1 were clean.  some of those commits both removed chapter1 AND added content elsewhere, so I think my first strategy is the best one.

**Comment by laumurph** [comment]
I'll try that out then. I can close the first couple of chapters and add those to the new fork. Then we can see how well that works before going forward.

**Pull request closed without merging**
