### PR TITLE
ENH: "swap int values" exercise with a basic test

### PR DESCRIPTION
**Pull request by yarikoptic**
I will not disclose a solution here, but it is a pure algebra, which is what I like

Ideally testing should be extended to assure that

- no hardcoded values (e.g. `7`) are used
- no smart student which uses `del` ;-)

### CODE REVIEW

**Comment by yarikoptic** [comment]
Think harder... No tuples, variables and algebra only - IMHO very much inline with the chapter

**Comment by yarikoptic** [comment]
BTW, iirc at least 33% if my non-CS grad students did it, then another 33% hardcoded a part of the solution (used 7, so they got it half way)

**Comment by bnmnetp** [comment]
OK, so I see the algebraic way, there is also the XOR solution which I knew about because Seymour Cray used it to swap registers.   I would be ok with this if it was in the exercises section.  But I think this is exacly the kind of problem that discourages many students from continuing.  What on earth is the motivation for this?  It’s the same number of lines of code.  What is wrong with using a third variable? (Nothing in my opinion). This just says you should be good at algebra to continue in this class.  The fact that only 33% of your undergrads got it right is more than I would expect from most schools, and in my opinion  very disappointing.

**Comment by yarikoptic** [comment]
Yeap - valid concerns! And I leave it up to you (no hurt feelings) on either to take it one way or another. I just didn't want to keep it all to myself.
Myself, I always liked "brain teasers" where the solution is not obvious and requires thinking "outside the box", and try to challenge my students the same way whenever I come about something tricky. This "problem" I actually remembered from high school programming classes ;-) Even though not always pragmatically valuable, such teasers are IMHO as useful as showing them some related funny videos, like I showed them the [Gary's WAT](https://www.destroyallsoftware.com/talks/wat) after they learned basic variables/lists. So, I wonder if to be accepted, it might be worth either annotating it as a "teaser" or even establish a new branch to collect similar ones for future addition as a new subsection of a kind?
Another aspect -- repetition is good.  That is what I liked in the fopp at times that questions go back a section of two thus causing memory recall. This "swap the numbers" then could be reminded about when talking about the natural pythonic way (tuples unpacking) to swap a number of values.
And once again -- completely up to you guys either to drop it or keep it in a backburner or ...

Cheers!

**Comment by bnmnetp** [comment]
If you move it to the exercises section.  The section it is in is meant to be used like a quiz to really assess how the students are getting the material, and is likely to be under time pressure.  I think stating that it is a kind of brain teaser and having it in the Exercises section is good.

**Comment by yarikoptic** [comment]
ok, moved (and extended description a bit, mentioning "hard-code" which was a part of the section IIRC following that UpdatingVariables section), but didn't check yet if all kosher

**Pull request closed without merging**
